# Generated by Django 2.2.2 on 2019-06-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipping', '0001_initial'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='order',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='audits', to='shop.Order'),
        ),
    ]
